### ISSUE TITLE
M1 support and/or Docker Image

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/numpythia#52]
Hi all,

thanks for this awesome package. I tried installing this on a M1 Mac, and it unsurprisingly failed. I was curious, would it be possible to provide a docker image or similar for numpythia?

**Comment by eduardo-rodrigues** [comment]
Hi @lukasheinrich, as you may know, this package has been lacking a maintainer since a while and developments and maintenance is on a case-by-case basis and minimal. I guess one of us org admins could prepare a docker image but it is probably faster if you do it, if you have the experience for it. Of course other updates such as the Pythia version would be even more welcome IMO.

**Comment by eduardo-rodrigues** [comment]
Closing since there is no appetite for it.
